# Generated by Django 4.2.7 on 2023-11-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
